openapi: 3.0.0
info:
  title: HNG Boilerplate API
  version: 1.0.0
servers:
  - url: http://
    description: Production Server
components:
  securitySchemes:
    BearerAuth:
      type: http
      bearerFormat: JWT
      scheme: bearer
path:
 /auth/signup:
    post:
      tags:
        - Auth
      summary: Create a new account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        '201':
          description: User created successfully
        '400':
          description: Invalid input
  /auth/login:
    post:
      tags:
        - Auth
      summary: Sign in to account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        '200':
          description: Login successful
        '401':
          description: Invalid credentials
  /auth/social-login:
    post:
      tags:
        - Auth
      summary: Social authentication login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                provider:
                  type: string
                token:
                  type: string
      responses:
        '200':
          description: Social login successful
        '401':
          description: Social login failed
  /auth/magic-link:
    post:
      tags:
        - Auth
      summary: Request a magic link for passwordless login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
      responses:
        '200':
          description: Magic link sent successfully
        '404':
          description: Email not found

/organizations:
    post:
      summary: Create a new organization
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
        responses:
          '201':
            description: Organization created
  /organizations/{id}:
    get:
      summary: Get organization details
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Organization details retrieved
        '404':
          description: Organization not found
    put:
      summary: Update organization details
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
        responses:
          '200':
            description: Organization updated
    delete:
      summary: Delete an organization
      security:
        - BearerAuth: []
      responses:
        '204':
          description: Organization deleted