openapi: 3.0.0
info:
  title: HNG Boilerplate API
  version: 1.0.0
servers:
  - url: http://
    description: Production Server
components:
  securitySchemes:
    BearerAuth:
      type: http
      bearerFormat: JWT
      scheme: bearer
path:
